#!/bin/bash -e
opts=( )
while [ $# -gt 0 ]; do
  case "$1" in
    --) shift; break;;
    -*) opts=("${opts[@]}" "$1"); shift;;
    *)  break;;
  esac
done
for i; do
  echo "$i"
  ./pplex.byte -s "${opts[@]}" "$i" | ./pplex.byte -r "${opts[@]}" - | cmp "$i" /dev/stdin
done
