(* COMMENT, SYMBOL, LIDENT, INT, BLANKS, NEWLINE *)
let x  =  42
(* UIDENT, ESCAPED_IDENT, INT32, INT64, NATIVEINT, CHAR, STRING *)
let (Some (+)) = Some (42l, 42L, 42n, 4.2, '?', '\'', '\n',
                       "string", "\t\n\"'", "
",'
')
(* LINE_DIRECTIVE *)
# 42
# 42 "somefilename.ml"
(* LABEL, OPTLABEL *)
let f ~x ?y = (x, y)
(* QUOTATION, ANTIQUOT *)
<<foo>> <:bar<baz>> <<foo$bar$baz>> <:bar<foo$bar$baz>>
(* NOTE that KEYWORD is never generated by this lexer *)
